### ISSUE TITLE
Googleアナリティクスの準備をする

### ISSUE THREAD

**Issue by sasasa** [sasasa/koen#49]
サーバーへの設置の後に設定をお願いいたします。

**Comment by sasasa** [comment]
サイトマップXML
https://kouen-map.com/sitemap.xml

時間のある時で結構ですので Google Search Console や 
Googleアナリティクス の設定をお願いします。

**Comment by ghost** [comment]
Analyticsのグローバルサイトタグ取得しました。

````
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-94JNEZ8R96"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-94JNEZ8R96');
</script>
````

**Comment by ghost** [comment]
サーチコンソールへの登録は、ドメインプロパティとURLプレフィックスプロパティのどちらが良いのか調べてからにします。お待ちください。

**Comment by ghost** [comment]
サーチコンソールへの登録でサイトの所有者確認する際に、HTMLファイルの有無による判断を選びました。
 `Laravel/koen/public` に `google9372569b25147eda.html` をアップロードしました。
念の為に内容も貼り付けておきます。
````
google-site-verification: google9372569b25147eda.html
````

**Comment by ghost** [comment]
XMLサイトマップをサーチコンソールに登録しました。
